server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  #############################新增网关配置#############################
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_route1 #payment_route   #路由的ID，没有固定的规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001         #匹配之后提供服务的路由地址
          uri: lb://cloud-payment-service     # lb: 是指路由的一种通讯协议，它实现了负载均衡通信功能
          predicates:
            - Path=/payment/get/**            #断言，路径相匹配的进行路由

        - id: payment_route2 #payment_route   #路由的ID，没有固定的规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001         #匹配之后提供服务的路由地址
          uri: lb://cloud-payment-service     # lb: 是指路由的一种通讯协议，它实现了负载均衡通信功能
          predicates:
            - Path=/payment/lb/**             #断言，路径相匹配的进行路由
            - After=2023-03-28T19:00:00.000+08:00[Asia/Shanghai]
            #- Cookie=username, test
            #- Header=X-Request-Id, \d+        #请求头要有X-Request-Id属性并且为整数的正则表达式
  ###################################################################


eureka:
  instance:
    hostname: cloud-gateway-service
  client: #服务提供者provider注册进eureka服务列表内
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka