server:
  port: 80

spring:
  application:
    name: cloud-consumer-order
#consul注册中心地址
  cloud:
    consul:
      host: localhost
      post: 8500
      discovery:
        service-name: ${spring.application.name}